# Generated by Django 3.1.6 on 2021-02-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catchallurl',
            name='last_referer',
            field=models.URLField(max_length=400, null=True),
        ),
    ]
