# https://github.com/casey/just
# https://just.systems/

dev:
    echo "This will constantly build and copy executable to ~/bin/gg"
    bun build --watch src/index.ts --target=bun --outfile ~/bin/gg --compile --bytecode

install:
    bun install

build:
    bun run compile

upgrade:
    bun update --interactive --minimum-release-age=86400 && bun install

