# Generated by Django 2.1.4 on 2018-12-27 19:55

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20181221_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(max_length=400)),
                ('original_q', models.CharField(max_length=400, null=True)),
                ('documents_found', models.PositiveIntegerField()),
                ('search_time', models.DurationField()),
                ('search_times', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('search_terms', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=400), default=list, size=2), default=list, size=None)),
                ('keywords', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
