# Generated by Django 2.1.4 on 2018-12-28 17:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_searchresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postprocessing',
            name='notes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=400), default=list, size=None),
        ),
    ]
