# Generated by Django 2.2.1 on 2019-05-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20181228_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='postprocessing',
            name='original_url',
            field=models.URLField(max_length=400, null=True),
        ),
    ]
