# Generated by Django 2.2.1 on 2019-05-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_postprocessing_original_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDNPurgeURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=400)),
                ('attempted', models.DateTimeField(null=True)),
                ('processed', models.DateTimeField(null=True)),
                ('cancelled', models.DateTimeField(null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('exception', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
