# Generated by Django 2.2.4 on 2019-09-03 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_cdnpurgeurl'),
    ]

    operations = [
        migrations.RunSQL("""
            CREATE INDEX
            base_postprocessing_created_duration_not_null_idx
            ON base_postprocessing (created)
            WHERE duration IS NOT NULL
        """)
    ]
