# Generated by Django 3.1.3 on 2020-11-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20191231_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandrun',
            name='options',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='keywords',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='search_times',
            field=models.JSONField(default=dict),
        ),
    ]
