# Generated by Django 4.2.13 on 2024-07-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('uuid', models.CharField(max_length=400)),
                ('url', models.CharField(max_length=400)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(default=dict)),
                ('data', models.JSONField(default=dict)),
            ],
        ),
    ]
