# Generated by Django 4.2.14 on 2024-07-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_analyticsevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='uuid',
            field=models.UUIDField(),
        ),
    ]
