# Generated by Django 4.2.14 on 2024-07-31 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_analyticsevent_url_alter_analyticsevent_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsGeoEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('country_code', models.CharField(max_length=2, null=True)),
                ('region', models.CharField(max_length=10, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lookup', models.JSONField(default=dict)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.analyticsevent')),
            ],
        ),
    ]
