# Generated by Django 4.2.15 on 2024-08-21 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_analyticsgeoevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsReferrerEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer', models.URLField(max_length=500)),
                ('pathname', models.URLField(max_length=300, null=True)),
                ('direct', models.BooleanField(default=False)),
                ('search_engine', models.CharField(max_length=100, null=True)),
                ('search', models.CharField(max_length=300, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.analyticsevent')),
            ],
        ),
    ]
