# Generated by Django 5.2.1 on 2025-06-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_analyticsevent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('status_code', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('request', models.JSONField(default=dict)),
                ('response', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
            ],
        ),
    ]
