# Generated by Django 5.2.3 on 2025-06-30 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_requestlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommandRun',
        ),
    ]
