# Generated by Django 5.2.3 on 2025-07-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_analyticsgeoevent_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsreferrerevent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
