# Generated by Django 5.2.4 on 2025-08-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_analyticsreferrerevent_created'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='analyticsevent',
            name='base_analyticsevent_created',
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
