# Generated by Django 5.2.5 on 2025-08-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_remove_analyticsevent_base_analyticsevent_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsRollupsDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('count', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analytics Rollups daily',
            },
        ),
    ]
