# Generated by Django 5.2.5 on 2025-08-25 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_analyticsrollupsdaily'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticsrollupsdaily',
            name='url',
        ),
    ]
