# Generated by Django 5.2.5 on 2025-08-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_remove_analyticsrollupsdaily_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsrollupsdaily',
            name='day',
            field=models.DateTimeField(db_index=True),
        ),
    ]
