# Generated by Django 5.2.5 on 2025-08-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_analyticsrollupsdaily_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsRollupsPathnameDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(db_index=True)),
                ('count', models.IntegerField()),
                ('pathname', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analytics Rollups by Pathname daily',
            },
        ),
    ]
