# Generated by Django 5.2.6 on 2025-09-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_analyticsrollupspathnamedaily'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLogRollupsBotAgentStatusCodeDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(db_index=True)),
                ('count', models.IntegerField()),
                ('bot_agent', models.CharField(max_length=100, null=True)),
                ('status_code', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': ' RequestLog Rollups by Bot Agent and Status Code daily',
            },
        ),
    ]
