# Generated by Django 5.2.7 on 2025-10-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_requestlogrollupsbotagentstatuscodedaily'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsRollupCommentsReferrerDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(db_index=True)),
                ('count', models.IntegerField()),
                ('referrer', models.URLField()),
                ('pathname', models.CharField(max_length=300)),
                ('is_bot', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analytics Rollup Comments by Referrer and Pathname daily',
            },
        ),
    ]
