# Generated by Django 5.2.8 on 2025-11-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_analyticsrollupcommentsreferrerdaily'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLogRollupsQuerystringDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(db_index=True)),
                ('count', models.IntegerField()),
                ('path', models.CharField(max_length=600)),
                ('querystring', models.CharField(max_length=600)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': ' RequestLog Rollups by query string daily',
            },
        ),
    ]
