# Generated by Django 2.2.11 on 2020-04-27 14:01

from django.db import migrations, models


def set_all_texts(apps, schema_editor):
    Card = apps.get_model("chiveproxy", "Card")
    for card in Card.objects.filter(text=""):
        card.text = (card.data.get("text") or "")[:200]
        card.save()


class Migration(migrations.Migration):

    dependencies = [
        ("chiveproxy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="text",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.RunPython(set_all_texts),
        migrations.RunSQL(
            """
            CREATE INDEX
                chiveproxy_card_text_idx
            ON
                chiveproxy_card
            USING GIN
                (to_tsvector('english', text))
        """
        ),
    ]
