# Generated by Django 3.1.3 on 2020-11-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiveproxy', '0002_card_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
