# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 13:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasttime', '0019_auto_20170111_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
