# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasttime', '0020_episode_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
