# Generated by Django 3.1.3 on 2020-11-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasttime', '0022_auto_20170302_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='metadata',
            field=models.JSONField(null=True),
        ),
    ]
