# Generated by Django 5.2.7 on 2025-11-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMCall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('messages', models.JSONField()),
                ('message_hash', models.CharField(default='', max_length=255)),
                ('temperature', models.IntegerField(null=True)),
                ('response', models.JSONField()),
                ('model', models.CharField(max_length=255)),
                ('error', models.TextField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('took_seconds', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
