# Generated by Django 6.0.4 on 2026-05-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llmcalls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmcall',
            name='use_case',
            field=models.CharField(default='', max_length=255),
        ),
    ]
