# Generated by Django 3.1.3 on 2020-11-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bayesdata',
            name='options',
            field=models.JSONField(),
        ),
    ]
