# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("awspa", "0001_initial")]

    operations = [
        migrations.AlterUniqueTogether(
            name="awsproduct", unique_together=set([("keyword", "asin", "searchindex")])
        )
    ]
