# Generated by Django 2.2.8 on 2020-01-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awspa', '0004_auto_20171204_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsproduct',
            name='paapiv5',
            field=models.BooleanField(default=False),
        ),
    ]
