# Generated by Django 2.2.10 on 2020-02-23 02:09

import django.contrib.postgres.fields
from django.db import migrations, models


def move_keyword_to_keywords(apps, schema_editor):
    AWSProduct = apps.get_model("awspa", "AWSProduct")
    for product in AWSProduct.objects.all():
        AWSProduct.objects.filter(id=product.id).update(keywords=[product.keyword])


class Migration(migrations.Migration):

    dependencies = [
        ("awspa", "0005_awsproduct_paapiv5"),
    ]

    operations = [
        migrations.AddField(
            model_name="awsproduct",
            name="keywords",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100), default=list, size=None
            ),
        ),
        migrations.AlterUniqueTogether(name="awsproduct", unique_together=set(),),
        migrations.RunPython(move_keyword_to_keywords),
    ]
