# Generated by Django 2.2.10 on 2020-02-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awspa', '0006_auto_20200222_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awsproduct',
            name='paapiv5',
            field=models.BooleanField(default=True),
        ),
    ]
