# Generated by Django 3.1.3 on 2020-11-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awspa', '0007_auto_20200222_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awsproduct',
            name='payload',
            field=models.JSONField(),
        ),
    ]
