# Generated by Django 3.1.3 on 2020-11-05 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awspa', '0008_auto_20201105_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awsproduct',
            name='paapiv5',
        ),
    ]
