# Generated by Django 2.0.5 on 2018-05-23 00:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Minimization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("result", django.contrib.postgres.fields.jsonb.JSONField()),
                ("time_took", models.FloatField()),
                ("add_date", models.DateTimeField(auto_now_add=True)),
            ],
        )
    ]
