# Generated by Django 2.0.5 on 2018-05-23 20:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minimalcss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='minimization',
            name='error',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='minimization',
            name='result',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
