# Generated by Django 3.1.3 on 2020-11-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimalcss', '0002_auto_20180523_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minimization',
            name='error',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='minimization',
            name='result',
            field=models.JSONField(null=True),
        ),
    ]
