name: Run

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  run-django:
    runs-on: ubuntu-latest

    steps:
      - name: Redis Server in GitHub Actions
        uses: supercharge/redis-github-action@v2
        with:
          redis-version: "7"

      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          # Version of PostgreSQL to use
          postgresql version: "16"
          postgresql db: peterbecom
          postgresql user: user
          postgresql password: secret

      - uses: actions/checkout@v6

      - name: Install uv
        id: setup-uv
        uses: astral-sh/setup-uv@v7

      - name: Celebrate uv cache hit
        if: steps.setup-uv.outputs.cache-hit == 'true'
        run: echo "Cache was restored"

      - name: Set up Python
        run: uv python install 3.12

      - name: Install the project
        run: uv sync

      - name: Install system dependencies
        run: |
          set -ex

          sudo apt-get install pngquant libjpeg-progs

          # 'jpegtran --version' fails, hence the '|| echo'
          which jpegtran || echo "jpegtran installed"

          pngquant --version
          which pngquant

      - name: Run gunicorn server
        run: |
          ./scripts/ci-run.sh
          ./bin/run.sh web > /tmp/stdout.log 2> /tmp/stderr.log &

      - name: Navigate to the server
        run: |
          sleep 3
          echo "HEALTHCHECK"
          curl --retry-connrefused --retry 4 --fail http://localhost:8000/api/v0/__healthcheck__
          echo "WHOAMI"
          curl --fail http://localhost:8000/api/v0/whoami
          echo "ROBOTS.TXT"
          curl --fail http://localhost:8000/robots.txt

      - name: Debug any server outputs
        if: failure()
        run: |
          echo "___NETSTAT___"
          netstat -nplt
          echo "____STDOUT____"
          cat /tmp/stdout.log
          echo "____STDERR____"
          cat /tmp/stderr.log
