# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("plog", "0010_blogitemtotalhits")]

    operations = [
        migrations.AddField(
            model_name="blogitemhit",
            name="http_accept_language",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogitemhit",
            name="http_referer",
            field=models.URLField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name="blogitemhit",
            name="http_user_agent",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogitemhit",
            name="remote_addr",
            field=models.GenericIPAddressField(null=True),
        ),
    ]
