# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    # dependencies = [("awspa", "0001_initial"), ("plog", "0012_onetimeauthkey")]
    dependencies = [("plog", "0012_onetimeauthkey")]

    operations = [
        # migrations.AddField(
        #     model_name="blogitem",
        #     name="awspa_products",
        #     field=models.ManyToManyField(to="awspa.AWSProduct"),
        # )
    ]
