# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("plog", "0013_blogitem_awspa_products")]

    operations = [
        # migrations.RemoveField(model_name="blogitem", name="awspa_products")
    ]
