# Generated by Django 2.0.5 on 2018-05-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("plog", "0014_remove_blogitem_awspa_products")]

    operations = [
        migrations.AddField(
            model_name="blogitem",
            name="open_graph_image",
            field=models.CharField(max_length=400, null=True),
        )
    ]
