# Generated by Django 2.1.7 on 2019-03-19 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plog', '0017_blogcomment_modify_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='akismet_pass',
        ),
    ]
