# Generated by Django 2.2 on 2019-04-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plog', '0018_remove_blogcomment_akismet_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogitemhit',
            name='page',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
