# Generated by Django 2.2.1 on 2019-05-16 14:46

from django.conf import settings
from django.db import migrations, models


def create_default_patterns(apps, schema_editor):
    SpamCommentPattern = apps.get_model("plog", "SpamCommentPattern")
    for pattern in settings.SPAM_URL_PATTERNS:
        SpamCommentPattern.objects.create(pattern=pattern, is_url_pattern=True)


class Migration(migrations.Migration):

    dependencies = [("plog", "0019_blogitemhit_page")]

    operations = [
        migrations.CreateModel(
            name="SpamCommentPattern",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pattern", models.CharField(max_length=200)),
                ("is_regex", models.BooleanField(default=False)),
                ("is_url_pattern", models.BooleanField(default=False)),
                ("kills", models.PositiveIntegerField(default=0)),
                ("add_date", models.DateTimeField(auto_now_add=True)),
                ("modify_date", models.DateTimeField(auto_now=True)),
            ],
            options={"unique_together": {("pattern", "is_regex", "is_url_pattern")}},
        ),
        migrations.RunPython(create_default_patterns),
    ]
