# Generated by Django 2.2.1 on 2019-06-02 00:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plog', '0020_spamcommentpattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCommentGeoLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('blog_comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plog.BlogComment')),
            ],
        ),
    ]
