# Generated by Django 2.2.3 on 2019-07-28 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plog', '0021_blogcommentgeolookup'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogItemDailyHits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_hits', models.IntegerField(default=0)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('blogitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plog.BlogItem')),
            ],
        ),
    ]
