# Generated by Django 2.2.4 on 2019-08-29 01:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


def forwards(apps, schema_editor):
    BlogComment = apps.get_model("plog", "BlogComment")
    BlogCommentGeoLookup = apps.get_model("plog", "BlogCommentGeoLookup")
    qs = BlogCommentGeoLookup.objects.filter(lookup__isnull=False)
    for blog_comment_id, lookup in qs.values_list("blog_comment_id", "lookup"):
        BlogComment.objects.filter(id=blog_comment_id).update(geo_lookup=lookup)


class Migration(migrations.Migration):

    dependencies = [("plog", "0022_blogitemdailyhits")]

    operations = [
        migrations.AddField(
            model_name="blogcomment",
            name="geo_lookup",
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.RunPython(forwards),
    ]
