# Generated by Django 2.2.4 on 2019-08-29 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plog', '0023_blogcomment_lookup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogCommentGeoLookup',
        ),
    ]
