# Generated by Django 2.2.8 on 2019-12-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plog', '0024_delete_blogcommentgeolookup'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='auto_approved',
            field=models.BooleanField(default=False),
        ),
    ]
