# Generated by Django 2.2.8 on 2020-01-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plog', '0025_blogcomment_auto_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogitem',
            name='popularity',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
