# Generated by Django 2.2.8 on 2020-01-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plog', '0026_blogitem_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogitem',
            name='archived',
            field=models.DateTimeField(null=True),
        ),
    ]
