# Generated by Django 2.2.10 on 2020-02-29 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plog', '0027_blogitem_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogitemhit',
            name='http_accept_language',
        ),
        migrations.RemoveField(
            model_name='blogitemhit',
            name='http_user_agent',
        ),
    ]
