# Generated by Django 4.2.16 on 2024-11-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plog', '0029_auto_20201105_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpamCommentSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('email', models.CharField(max_length=300, null=True)),
                ('kills', models.PositiveIntegerField(default=0)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
