# Generated by Django 4.2.16 on 2024-11-03 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plog', '0030_spamcommentsignature'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCommentClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('classification', models.CharField(max_length=100)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('blogcomment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plog.blogcomment')),
            ],
        ),
    ]
