# Generated by Django 4.2.16 on 2024-11-05 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plog', '0031_blogcommentclassification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcommentclassification',
            name='blogcomment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plog.blogcomment'),
        ),
    ]
