# Generated by Django 6.0 on 2025-12-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plog', '0032_alter_blogcommentclassification_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='highlighted',
            field=models.DateTimeField(null=True),
        ),
    ]
