# Generated by Django 6.0 on 2025-12-16 14:49

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plog', '0033_blogcomment_highlighted'),
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, max_length=100)),
                ('popularity', models.FloatField(default=0.0)),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('index_version', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['term'], name='plog_searchterm_term_gin_idx', opclasses=['gin_trgm_ops'])],
                'unique_together': {('term', 'index_version')},
            },
        ),
    ]
