# Generated by Django 6.0 on 2025-12-30 02:45

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plog', '0034_searchterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('title_search_vector', django.contrib.postgres.search.SearchVectorField(verbose_name='title')),
                ('text', models.TextField()),
                ('text_search_vector', django.contrib.postgres.search.SearchVectorField(verbose_name='text')),
                ('popularity', models.FloatField(default=0.0)),
                ('date', models.DateTimeField()),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list)),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('source_modify_date', models.DateTimeField()),
                ('index_version', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['title_search_vector'], name='plog_search_title_s_ecc455_gin'), django.contrib.postgres.indexes.GinIndex(fields=['text_search_vector'], name='plog_search_text_se_cba5d5_gin'), django.contrib.postgres.indexes.GinIndex(fields=['title'], name='plog_searchdoc_title_gin_idx', opclasses=['gin_trgm_ops'])],
                'unique_together': {('oid', 'index_version')},
            },
        ),
    ]
