# Generated by Django 6.0 on 2026-01-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plog', '0035_searchdoc'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blogcomment',
            index=models.Index(condition=models.Q(('parent__isnull', True)), fields=['add_date'], name='add_date_when_parent_null'),
        ),
    ]
