# Generated by Django 6.0.6 on 2026-06-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plog', '0036_blogcomment_add_date_when_parent_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogitem',
            name='is_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='OneTimeAuthKey',
        ),
    ]
