# Generated by Django 6.0.1 on 2026-02-15 20:10

from pgvector.django import VectorExtension
import pgvector.django.vector

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plog', '0036_blogcomment_add_date_when_parent_null'),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='searchdoc',
            name='title_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AddField(
            model_name='searchdoc',
            name='text_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.RunSQL("""
            CREATE INDEX plog_search_title_embedding_idx
            ON plog_searchdoc
            USING ivfflat (title_embedding vector_cosine_ops)
            WITH (lists = 100)
        """),
        migrations.RunSQL("""
            CREATE INDEX plog_search_text_embedding_idx
            ON plog_searchdoc
            USING ivfflat (text_embedding vector_cosine_ops)
            WITH (lists = 100)
        """),
    ]
