# Generated by Django 6.0.6 on 2026-06-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plog', '0037_blogitem_is_photo_delete_onetimeauthkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogfile',
            name='is_open_graph_image',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
