# Generated by Django 6.0.6 on 2026-07-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plog', '0038_blogfile_is_open_graph_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdoc',
            name='is_photo',
            field=models.BooleanField(default=False),
        ),
    ]
